### ISSUE TITLE
No game 赌约

### ISSUE THREAD

**Issue by xiaoyueyue165** [xiaoyueyue165/blog#13]
@yue 
如果玩了一次游戏，你和我说一下，从那天算起，一年不要和我说话，我也不和你说话，这怎么样

@hy
你真好，真的，这个办法也好，我怕自己失言，但这是最好的戒掉的办法

@yue
你如果答应了，就要小心谨慎了，上面我打的是一年

@hy
嗯，我答应你

@yue
这就包括你自己不能玩，你同事让你陪他玩也不能玩，只要打开界面就算，目的是不让你玩游戏，不是让我们沉默一年

@hy
我明白

**Comment by miaoyuxinbaby** [comment]
原谅我，笑了。噗噗噗噗噗，抱歉，抱歉
